version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing dependencies"
      - pip3 install -r requirements.txt

  pre_build:
    commands:
      - echo "Executing pre-build commands"

  build:
    commands:
      - echo "Build started"
      # Add any additional build steps if needed

  post_build:
    commands:
      - echo "Build completed"

artifacts:
  files: '**/*'
  discard-paths: yes
  base-directory: '/'
